### ISSUE TITLE
强名称支持

### ISSUE THREAD

**Issue by modcrafts** [dotnet-campus/dotnetCampus.Configurations#58]
对项目进行强名称签名以便拥有强名称的项目使用此项目进行开发
`引用程序集“dotnetCampus.Configurations, Version=1.6.10.0, Culture=neutral, PublicKeyToken=null”没有强名称。`
**参见:** https://docs.microsoft.com/zh-cn/dotnet/standard/assembly/create-use-strong-named

**Comment by lindexi** [comment]
@modcrafts 不做强签名，如果你有需求，可以你自己签名

强签的优势在于可以证明发布者，不足在于证书链管理和友元不方便以及校验耗时
