### ISSUE TITLE
在WPF的Startup执行写入之后，立即关闭进程，无法写入保存

### ISSUE THREAD

**Issue by wutangyuan** [dotnet-campus/dotnetCampus.Configurations#59]
发现了一个问题，在Startup写入执行配置的写入操作，写完之后关闭进程，无法正常的写入。
在关闭进程之前，await Task.Delay(1000)，可以正常写入
可能需要支持同步写入的方式？

**Comment by lindexi** [comment]
@wutangyuan 有开放异步写入，可以在主函数做异步写入等待
