### ISSUE TITLE
监听后，文件内容发生了改变，可能无法读到文件的新值

### ISSUE THREAD

**Issue by lindexi** [dotnet-campus/dotnetCampus.Configurations#9]
![图片](https://user-images.githubusercontent.com/16054566/74727540-4aa57080-527c-11ea-9c32-6cbd720846fc.png)

请看 https://github.com/dotnet-campus/dotnetCampus.Configurations/runs/448793430

**Comment by walterlv** [comment]
This is fixed by #29
